---
- hosts: all
  become: true
  vars:
      home: /home/vagrant
      document_root: /vagrant
      go_path: /vagrant
  pre_tasks:
      - name: Update apt cache
        apt:
          update_cache=yes
          cache_valid_time=7200
      - name: Install required packages
        apt: 
          name:
            - git
            - exuberant-ctags
            - tig
            - gdb
            - cgdb
            - autoconf
            - libtool
            - make
            - tree
            - htop
            - tmux
            - man-db
          state: present
          autoclean: yes
  tasks:
      - name: Create go src directory
        file:
            dest={{ go_path }}/src/github.com
            state=directory
            recurse=yes
            owner=vagrant
            group=vagrant
  roles:
      - { role: dotfiles, become: no }
      - { role: golang, become: no }
      - { role: vim, become: no }
      - { role: youcompleteme, become: no }
